name: Productivity

on:
  schedule:
    - cron: "30 3 * * *"

jobs:
  build:
    name: Profile Gist with Productive Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 48656ced75943ada1de0a79702345d6a
          TIMEZONE: Europe/Kirov