name: Covid Stats

on:
  schedule:
    - cron: "30 3 * * *"

jobs:
  build:
    name: Profile Gist with COVID Russia Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: puf17640/covid-box@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNTRY: Russia
          GIST_ID: d8f8fbbbeb108dc19ceae1e3dec3d3c3